"""empty message

Revision ID: 240000613db2
Revises: abaf02281128
Create Date: 2021-07-08 13:59:18.340648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240000613db2'
down_revision = 'abaf02281128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
