"""empty message

Revision ID: 819534d38d61
Revises: b679d78c26e1
Create Date: 2021-06-26 08:10:11.151731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819534d38d61'
down_revision = 'b679d78c26e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'name')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    op.drop_table('authors')
    # ### end Alembic commands ###
